/*-------------------------------------------------------------------------
 *
 * pg_propgraph_element_label_d.h
 *    Macro definitions for pg_propgraph_element_label
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_PROPGRAPH_ELEMENT_LABEL_D_H
#define PG_PROPGRAPH_ELEMENT_LABEL_D_H

/* Macros related to the structure of pg_propgraph_element_label */

#define PropgraphElementLabelRelationId 8305
#define PropgraphElementLabelObjectIndexId 8312
#define PropgraphElementLabelElementLabelIndexId 8313
#define PropgraphElementLabelLabelIndexId 8317

#define Anum_pg_propgraph_element_label_oid 1
#define Anum_pg_propgraph_element_label_pgellabelid 2
#define Anum_pg_propgraph_element_label_pgelelid 3

#define Natts_pg_propgraph_element_label 3

/* Definitions copied from pg_propgraph_element_label.h */


/* OID symbols for objects defined in pg_propgraph_element_label.dat */


#endif							/* PG_PROPGRAPH_ELEMENT_LABEL_D_H */
